Repository johnkallstrom/GarageThree, pull requests merged in 2024-05, with the labels that each got.

#1 Automapper
  GarageThree.Web/GarageThree.Web.csproj
  GarageThree.Web/GlobalUsings.cs
  GarageThree.Web/Mappings/GarageProfile.cs
  GarageThree.Web/Mappings/MemberProfile.cs
  GarageThree.Web/Mappings/VehicleProfile.cs
  GarageThree.Web/Program.cs
  GarageThree.Web/ViewModels/Garage/GarageCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Garage/GarageViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleViewModel.cs
Labels: enhancement

#3 Update README.md
  README.md
Labels: documentation

#2 Seed Data
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
  .gitignore
  GarageThree.Core/Entities/Member.cs
  GarageThree.Core/Entities/Vehicle.cs
  GarageThree.Core/Entities/VehicleType.cs
  GarageThree.Core/Enums/Color.cs
  GarageThree.Persistence/Data/ApplicationDbContext.cs
  GarageThree.Persistence/Data/SeedData.cs
  GarageThree.Persistence/GarageThree.Persistence.csproj
  GarageThree.Persistence/Migrations/20240502080851_Initial.Designer.cs
  GarageThree.Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
  GarageThree.Persistence/Repositories/GarageRepository.cs
  GarageThree.Persistence/Repositories/IRepository.cs
  GarageThree.Persistence/Repositories/MemberRepository.cs
  GarageThree.Persistence/Repositories/VehicleRepository.cs
  GarageThree.Web/Extensions/WebAppExtensions.cs
  GarageThree.Web/Program.cs
  GarageThree.Web/Properties/launchSettings.json
  GarageThree.Web/ViewModels/Member/MemberIndexViewModel.cs
  GarageThree.Web/Views/Shared/Member/Index.cshtml
  GarageThree.Web/appsettings.DevContainers.json
Labels: enhancement

#4 Member Create
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/GlobalUsings.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/Views/Members/Create.cshtml
  GarageThree.Web/Views/Members/Index.cshtml
  GarageThree.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#6 Member Index Action ViewModel View
  GarageThree.Core/Entities/Garage.cs
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Program.cs
  GarageThree.Web/ViewModels/Garage/GarageCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Garage/GarageViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberIndexViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleTypeViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleViewModel.cs
  GarageThree.Web/Views/Members/Index.cshtml
  GarageThree.Web/Views/Shared/_Footer.cshtml
  GarageThree.Web/Views/Shared/_Layout.cshtml
  GarageThree.Web/Views/Shared/_Navbar.cshtml
Labels: enhancement

#7 Use Faker.Name + Faker.Internet.Email
  GarageThree.Persistence/Data/SeedData.cs
Labels: bug

#11 SSN Validation Attribute
  GarageThree.Web/GlobalUsings.cs
  GarageThree.Web/Validations/SocialSecurityNumberAttribute.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/appsettings.json
Labels: enhancement

#8 Use launch profile for seed data
  GarageThree.Web/Program.cs
  GarageThree.Web/Properties/launchSettings.json
  GarageThree.Web/ViewModels/Member/MemberViewModel.cs
Labels: enhancement

#13 Add Member Details Get Action + View
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/ViewModels/Member/MemberViewModel.cs
  GarageThree.Web/Views/Members/Details.cshtml
  GarageThree.Web/Views/Members/Index.cshtml
Labels: enhancement

#9 wwwroot
  GarageThree.Web/ViewModels/Member/MemberViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleViewModel.cs
  GarageThree.Web/wwwroot/css/styles.css
  GarageThree.Web/wwwroot/js/main.js
Labels: enhancement

#12 Member Edit Actions + View
  .gitignore
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/Views/Members/Edit.cshtml
  GarageThree.Web/Views/Shared/_Navbar.cshtml
Labels: enhancement

#16 Member Unique SSN Validation
  GarageThree.Persistence/Parameters/QueryParams.cs
  GarageThree.Persistence/Repositories/GarageRepository.cs
  GarageThree.Persistence/Repositories/IRepository.cs
  GarageThree.Persistence/Repositories/MemberRepository.cs
  GarageThree.Persistence/Repositories/VehicleRepository.cs
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Controllers/VehiclesController.cs
  GarageThree.Web/Validations/SocialSecurityNumberAttribute.cs
  GarageThree.Web/ViewModels/Enums/MessageType.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Message/MessageViewModel.cs
  GarageThree.Web/Views/Members/Create.cshtml
  GarageThree.Web/Views/Members/Index.cshtml
  GarageThree.Web/Views/Shared/_Navbar.cshtml
  GarageThree.Web/Views/_ViewImports.cshtml
Labels: enhancement

#15 Garage Index Action + View
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Controllers/VehiclesController.cs
  GarageThree.Web/Mappings/GarageProfile.cs
  GarageThree.Web/Program.cs
  GarageThree.Web/ViewModels/Garage/GarageIndexViewModel.cs
  GarageThree.Web/Views/Garages/Index.cshtml
Labels: enhancement

#18 Member Delete Action
  GarageThree.Persistence/Data/ApplicationDbContext.cs
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Controllers/VehiclesController.cs
  GarageThree.Web/GlobalUsings.cs
  GarageThree.Web/Program.cs
  GarageThree.Web/Services/BaseMessageService.cs
  GarageThree.Web/Services/GarageSelectListItemService.cs
  GarageThree.Web/Services/IMessageParameters.cs
  GarageThree.Web/Services/IMessageService.cs
  GarageThree.Web/Services/MessageParameters.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/Views/Garages/Index.cshtml
  GarageThree.Web/Views/Members/Create.cshtml
  GarageThree.Web/Views/Members/Index.cshtml
Labels: enhancement

#21 Member index search
  GarageThree.Persistence/Parameters/QueryParams.cs
  GarageThree.Persistence/Repositories/MemberRepository.cs
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Views/Members/Index.cshtml
Labels: enhancement

#22 Controller refactor
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Controllers/VehiclesController.cs
Labels: Refactor

#23 Sort Member In Index
  GarageThree.Persistence/Repositories/GarageRepository.cs
  GarageThree.Persistence/Repositories/MemberRepository.cs
  GarageThree.Persistence/Repositories/VehicleRepository.cs
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Program.cs
  GarageThree.Web/Services/ISortService.cs
  GarageThree.Web/Services/MemberSortService.cs
Labels: enhancement

#19 Garage Create Action + View
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Views/Garages/Create.cshtml
Labels: enhancement

#24 Garage/Member Vehicle Count Column
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Mappings/MemberProfile.cs
  GarageThree.Web/ViewModels/Garage/GarageViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberViewModel.cs
  GarageThree.Web/Views/Garages/Index.cshtml
  GarageThree.Web/Views/Members/Index.cshtml
Labels: enhancement

#26 Serve custom CSS via static files
  GarageThree.Web/Program.cs
  GarageThree.Web/Views/Garages/Index.cshtml
  GarageThree.Web/Views/Members/Index.cshtml
  GarageThree.Web/Views/Shared/_Layout.cshtml
  GarageThree.Web/wwwroot/css/styles.css
Labels: Refactor

#25 Garage details action view
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Views/Garages/Details.cshtml
Labels: enhancement

#20 Vehicle Index Search
  GarageThree.Persistence/Repositories/VehicleRepository.cs
  GarageThree.Web/Controllers/VehiclesController.cs
  GarageThree.Web/Services/GarageSelectListItemService.cs
  GarageThree.Web/Services/ISelectListItemService.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleViewModel.cs
  GarageThree.Web/Views/Vehicles/Index.cshtml
Labels: enhancement

#29 Garage Edit Action-View
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Views/Garages/Edit.cshtml
Labels: enhancement

#31 Garage delete action
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Views/Garages/Index.cshtml
Labels: enhancement

#32 Include vehicle count in Member Views
  GarageThree.Persistence/Repositories/MemberRepository.cs
  GarageThree.Web/Views/Members/Details.cshtml
Labels: enhancement

#34 Garage hourly rate
  GarageThree.Persistence/Data/SeedData.cs
  GarageThree.Web/ViewModels/Garage/GarageCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Garage/GarageViewModel.cs
  GarageThree.Web/Views/Garages/Create.cshtml
  GarageThree.Web/Views/Garages/Edit.cshtml
  GarageThree.Web/Views/Garages/Index.cshtml
Labels: enhancement

#33 Add Vehicle Edit Action + View
  GarageThree.Persistence/Repositories/VehicleRepository.cs
  GarageThree.Web/Controllers/VehiclesController.cs
  GarageThree.Web/Mappings/VehicleProfile.cs
  GarageThree.Web/Program.cs
  GarageThree.Web/Services/GarageSelectListItemService.cs
  GarageThree.Web/Services/MemberSelectListItemService.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleCreateViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleEditViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleViewModel.cs
  GarageThree.Web/Views/Vehicles/Create.cshtml
  GarageThree.Web/Views/Vehicles/Details.cshtml
  GarageThree.Web/Views/Vehicles/Edit.cshtml
  GarageThree.Web/Views/Vehicles/Index.cshtml
Labels: enhancement

#37 generate unique SSN
  GarageThree.Persistence/Data/SeedData.cs
Labels: Refactor

#38 MemberRepository Any/AnyAsync + New Member Success Message
  GarageThree.Persistence/Repositories/MemberRepository.cs
  GarageThree.Web/Controllers/MembersController.cs
Labels: bug, enhancement

#39 Various bug fixes
  GarageThree.Web/Controllers/GaragesController.cs
  GarageThree.Web/Controllers/MembersController.cs
  GarageThree.Web/Controllers/VehicleTypesController.cs
  GarageThree.Web/Controllers/VehiclesController.cs
  GarageThree.Web/Mappings/MemberProfile.cs
  GarageThree.Web/ViewModels/Garage/GarageCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Garage/GarageViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberCreateOrEditViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberCreateViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberEditViewModel.cs
  GarageThree.Web/ViewModels/Member/MemberViewModel.cs
  GarageThree.Web/ViewModels/Vehicle/VehicleViewModel.cs
  GarageThree.Web/ViewModels/VehicleType/VehicleTypeViewModel.cs
  GarageThree.Web/Views/Checkouts/Details.cshtml
  GarageThree.Web/Views/Garages/Details.cshtml
  GarageThree.Web/Views/Garages/Index.cshtml
  GarageThree.Web/Views/Members/Create.cshtml
  GarageThree.Web/Views/Members/Details.cshtml
  GarageThree.Web/Views/Members/Edit.cshtml
  GarageThree.Web/Views/VehicleTypes/Details.cshtml
  GarageThree.Web/Views/Vehicles/Details.cshtml
Labels: bug, Refactor
